### ISSUE TITLE
"049 INSULIN_DELIVERY_COMMAND" Pod failure after updating AAPS 

### ISSUE THREAD

**Issue by Dani501i** [AAPS-Omnipod/AndroidAPS#6]
Reporting bugs
--------------
**_- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem_**

30.09-2020 at 9:34PM, i got a pod failure right after opening the app when updating AAPS. The error is called "049 INSULIN_DELIVERY_COMMAND"

**_- Note the Build version (found in the About dialog in the app, when pressing the three dots in the_
  upper-right corner)._**

Build: EROS_0.2-1848-gf223a8fd7-2020.09.30-21:22

**_- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles_**

See attached file

[AndroidAPS_LOG_1601495353518.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5307968/AndroidAPS_LOG_1601495353518.log.zip)

**Comment by bartsopers** [comment]
This is known issue that happens when you update from an older version of omnipod_eros_dev (I believe from before the end of August) to a newer version, while having an active TBR. It only happens once. I announced this in the Discord channel a few times, but there's been a lot of messages there so I think it didn't reach everyone :-)
